### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pdashford** [types/sequelize#137]
Hi, when I run **npm install --save-dev types/sequelize** I get the following errors, would someone be able to assist?

```
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:1
1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit  types/sequelize resetting remote C:\Users\AshfordP\AppDat
a\Roaming\npm-cache\_git-remotes\git-github-com-types-sequelize-git-16fbe1d4 bec
ause of error: { Error: Command failed: git -c core.longpaths=true config --get
remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:342:1
1)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/sequelize.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-sequelize-git-16fb
e1d4: Cloning into bare repository 'C:\Users\AshfordP\AppData\Roaming\npm-cache\
_git-remotes\git-github-com-types-sequelize-git-16fbe1d4'...
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/sequelize.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-sequelize-git-16fb
e1d4: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/sequelize.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-sequelize-git-16fb
e1d4: github.com[0: 192.30.253.112]: errno=No error
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/sequelize.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-sequelize-git-16fb
e1d4: github.com[1: 192.30.253.113]: errno=No error
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit  types/validator#83990944fcc53bcb4b05b347c3cdfcb7aa05b3c7
resetting remote C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-remotes\git-gi
thub-com-types-validator-git-83990944fcc53bcb4b05b347c3cdfcb7aa05b3c7-df0aafd5 b
ecause of error: { Error: Command failed: git -c core.longpaths=true config --ge
t remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:198:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:891:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/validator.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-validator-git-8399
0944fcc53bcb4b05b347c3cdfcb7aa05b3c7-df0aafd5: Cloning into bare repository 'C:\
Users\AshfordP\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-valid
ator-git-83990944fcc53bcb4b05b347c3cdfcb7aa05b3c7-df0aafd5'...
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/validator.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-validator-git-8399
0944fcc53bcb4b05b347c3cdfcb7aa05b3c7-df0aafd5: fatal: unable to connect to githu
b.com:
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/validator.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-validator-git-8399
0944fcc53bcb4b05b347c3cdfcb7aa05b3c7-df0aafd5: github.com[0: 192.30.253.112]: er
rno=No error
npm ERR! git clone --template=C:\Users\AshfordP\AppData\Roaming\npm-cache\_git-r
emotes\_templates --mirror git://github.com/types/validator.git C:\Users\Ashford
P\AppData\Roaming\npm-cache\_git-remotes\git-github-com-types-validator-git-8399
0944fcc53bcb4b05b347c3cdfcb7aa05b3c7-df0aafd5: github.com[1: 192.30.253.113]: er
rno=No error
api@0.1.0 C:\Users\AshfordP\Documents\Private\briard-api
`-- @types/sequelize@4.0.0  (git+https://github.com/types/sequelize.git#505b409d
c42199abf5f0df5a9d9e86010850909f)
  `-- @types/validator@5.7.0  (git+https://github.com/types/validator.git#839909
44fcc53bcb4b05b347c3cdfcb7aa05b3c7)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
```

**Comment by felixfbecker** [comment]
This is offtopic for this repo, there seems to be an issue with your git or npm, please direct your question at those communities
